export const SET_LANGUAGE = "SET_LANGUAGE";

export const GET_FRANCHISE = "GET_FRANCHISE";
export const GET_LEAGUES = "GET_LEAGUES";
export const GET_SUBLEAGUES = "GET_SUBLEAGUES";
export const GET_CITIES = "GET_CITIES";

export const GET_NEWS = "GET_NEWS";
export const GET_MAIN_NEWS = "GET_MAIN_NEWS";
export const GET_CURRENT_NEWS = "GET_CURRENT_NEWS";
export const GET_STATS = "GET_STATS";

export const GET_ERRORS = "GET_ERRORS";

export const GET_SEASONS_INFO = "GET_SEASONS_INFO";
export const GET_TOUR_INFO = "GET_TOUR_INFO";
export const GET_TOUR_NEWS = "GET_TOUR_NEWS";
export const GET_TOUR_TABLE = "GET_TOUR_TABLE";
export const GET_TOUR_CALENDAR = "GET_TOUR_CALENDAR";
export const GET_TOUR_CALENDAR_BY_FILTER = "GET_TOUR_CALENDAR_BY_FILTER";
export const GET_TOUR_STATS = "GET_TOUR_STATS";
export const GET_FILTERED_STATS = "GET_FILTERED_STATS";
export const GET_TOUR_RESULTS = "GET_TOUR_RESULTS";
export const GET_TOUR_RESULTS_BY_FILTER = "GET_TOUR_RESULTS_BY_FILTER";
export const GET_TOUR_CLUBS = "GET_TOUR_CLUBS";
export const GET_TOUR_STADIUMS = "GET_TOUR_STADIUMS";
export const GET_TOUR_CONTACTS = "GET_TOUR_CONTACTS";
export const GET_TOUR_GAME = "GET_TOUR_GAME";
export const GET_TOUR_GAME_COMPOSITION = "GET_TOUR_GAME_COMPOSITION";
export const GET_TOUR_GAME_MEDIA = "GET_TOUR_GAME_MEDIA";
export const GET_TOUR_PLAYER = "GET_TOUR_PLAYER";
export const GET_TOUR_COMMAND = "GET_TOUR_COMMAND";
export const GET_TOUR_TEAM = "GET_TOUR_TEAM";
